### ISSUE TITLE
layout problems after refactoring css to sass

### ISSUE THREAD

**Issue by klaraborowska** [elharony/awesomeApp-Web#16]
There are problems with layout on smaller devices after refactoring css code to sass. 
![screenshot 2018-06-11 21 48 00](https://user-images.githubusercontent.com/33237744/41253830-d8e74aae-6dc1-11e8-92cf-06976bc3aefe.png)
![screenshot 2018-06-11 21 48 10](https://user-images.githubusercontent.com/33237744/41253837-dc575fb2-6dc1-11e8-83cc-119cb19c7274.png)

**Comment by elharony** [comment]
This responsive issue has been solved in the last commit.
Thanks for noticing this, @klaraborowska ! 👍
