### ISSUE TITLE
New Logo/Icon proposal

### ISSUE THREAD

**Issue by mansya** [elharony/awesomeApp-Web#18]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by elharony** [comment]
Hello @mansya ,

Thanks for your initiative!
You are totally welcome to create a logo for us. That would be a great contribution from you!

Thanks for offering this, and we are waiting to see your great example 👍

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? which one do you like ? If there is a change. please let me know. I made it in two models.
![awesomeapp-web](https://user-images.githubusercontent.com/33461607/44944207-f8109400-adfc-11e8-98de-cf0c47840e5c.png)

**Comment by elharony** [comment]
Hello @mansya 

Thanks for doing this to improve `AwesomeApp`, great work!
Unfortunately, it doesn't reflect a professional profile of how AwesomeApp should look like.

The current logo focus on the name, the `AA` nested together represents `AwesomeApp`.
Maybe you can take a look at the current logo and try to do something better if you want!

Again, we really appreciate your effort to improve AwesomeApp and we would like to see more contributions from you, @mansya! 😉

**Comment by mansya** [comment]
I will modify your logo as interesting as possible. give me time sir.

**Comment by mansya** [comment]
Hi sir. how about this design ? if you like tell me which one you like. tell me if there is a change sir.
![awesomeapp-web](https://user-images.githubusercontent.com/33461607/44956952-202fee00-aef6-11e8-8b89-ed3e73268e23.png)

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.

**Comment by elharony** [comment]
Sorry for being away!

I really liked it. Unfortunately, this App Development is almost stopped now as it was related to `Udacity`, and I have not associated with them anymore _(I've completed my Scholarship there)_ but if I started to work on this project again, I will use your awesome logo @mansya !

GREAT WORK! 👍
