### ISSUE TITLE
bug: Display 2 Project's deadline when clicking fast

### ISSUE THREAD

**Issue by elharony** [elharony/awesomeApp-Web#5]
**The Problem**
When the user clicks on a `project`, its `deadline` becomes `visible` below it. But, when clicking on two projects fast, both deadlines will be visible.

**Expected Solution**
Display one `deadline` only, and if the user `click` on another `project`, we need to hide the previous project's `deadline`. 

**Additional Explanation**
Check the image below:
![fast clicking on two projects bug](https://user-images.githubusercontent.com/16986422/39668222-ebb0f62e-50c7-11e8-8e5c-501259e56993.png)

**Comment by elharony** [comment]
This bug still exists after updating to our new layout

**Comment by ghost** [comment]
Already fixed in the last pull request -  Fixed JS after redesign #15

**Comment by elharony** [comment]
Yeah!
I forgot to close it. Thanks for reminding me, @Dimas-X ! 👍
